### ISSUE TITLE
:REFLINK :DEFINITION that looks like :EMPH

### ISSUE THREAD

**Issue by melisgl** [3b/3bmd#55]
Is this not valid input?

    (3bmd-grammar:parse-doc "[l][*x*]")
    .. debugger invoked on SB-KERNEL:CASE-FAILURE:
    ..   :EMPH fell through ETYPECASE expression.
    ..   Wanted one of (STRING CHARACTER LIST).

**Comment by 3b** [comment]
as far as i remember, markdown specifies that all input is valid input, so an error is definitely wrong there. Haven't had a chance to look at the specific case though, what interpretation would you expect from it?

**Comment by melisgl** [comment]
If there is a definition of `*x*`, then it should be used.  See this babelmark comparison:
https://babelmark.github.io/?text=%5Bl%5D%5B*x*%5D%0A%0A++%5B*x*%5D%3A+http%3A%2F%2Fexample.com

If there is no definition, then I'd expect to get `[l][*x*]` out. Not many implementations get this right: https://babelmark.github.io/?text=%5Bl%5D%5B*x*%5D%0A.

This means that `[l][*x*]` should be parsed as `(:REFERENCE-LINK :LABEL ("l") :DEFINITION "*x*")`.

**Comment by 3b** [comment]
Looks like CommonMark and original markdown parse it as  `<p>[l][<em>x</em>]</p>`, which seems like a reasonable interpretation (without a definition, `[][]` isn't a reference link, so contents should be processed normally.)

Your version is also reasonable, but I think I'd prefer to match CommonMark where practical.

**Comment by melisgl** [comment]
Yes, it makes more sense your way. Are you saying though that it wouldn't be parsed as a `:REFERENCE-LINK`? That would definitely make PAX's job harder because it to process `[some printer variables][*print-length*]` it currently only needs to consider `:REFERENCE-LINK`s.

**Comment by melisgl** [comment]
Thanks. That will be easy to accommodate in PAX.

**Comment by 3b** [comment]
pushed something to [rc branch](https://github.com/3b/3bmd/tree/rc) for this and  #57  (and some other things, like block quote printing as verbatim in md).

Ended up with just leaving it as `(:REFERENCE-LINK :LABEL ("1") :DEFINITION ((:EMPH "x")))` since that seemed to work with the existing code, and I didn't see any obvious way to get the original text within the rule. Not sure if it is worth rearranging the code a bit to use the printer to regenerate something like the input markdown there or just let the user do that themselves.

Let me know if that works and/or breaks anything for you, and I'll merge it at some point if it seems OK.

**Comment by melisgl** [comment]
It works fine with some followup changes in PAX: https://github.com/melisgl/mgl-pax/commits/3bmd-rc.
The only breakage was because `:DEFINITION` is now a parse tree, whereas it was a string. Plus, blockquotes are turned into html `<blockquote>`. Performance seems to be about the same.
